# Generated by Django 4.1.1 on 2022-10-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produs', models.IntegerField()),
                ('mobile', models.CharField(max_length=80)),
                ('cantitate', models.IntegerField()),
            ],
        ),
    ]
