# Generated by Django 4.1.1 on 2022-10-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('isAvailable', models.BooleanField(default=False)),
                ('isHot', models.BooleanField(default=False)),
                ('weight', models.ManyToManyField(to='produse.weight')),
            ],
        ),
    ]
