# Generated by Django 4.1.1 on 2022-10-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='image',
            field=models.ImageField(upload_to='./media'),
        ),
    ]
